### ISSUE TITLE
ERROR WHEN KILLING

### ISSUE THREAD

**Issue by kingvonx** [FesterHead/Quests#10]
[13:46:21 ERROR]: Could not pass event EntityDeathEvent to Quests v3.4.3-1.16.3
java.lang.NullPointerException: null
        at com.leonardobishop.quests.player.questprogressfile.QuestProgressFile.getQuestProgress(QuestProgressFile.java:341) ~[?:?]
        at com.leonardobishop.quests.quests.tasktypes.TaskType.processObject(TaskType.java:124) ~[?:?]
        at com.leonardobishop.quests.quests.tasktypes.types.Death.onMobKill(Death.java:43) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor174.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[Paper-1.16.3-latest.jar:git-Paper-253]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[Paper-1.16.3-latest.jar:git-Paper-253]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Paper-1.16.3-latest.jar:git-Paper-253]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[Paper-1.16.3-latest.jar:git-Paper-253]
        at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:801) ~[Paper-1.16.3-latest.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.EntityLiving.d(EntityLiving.java:1491) ~[Paper-1.16.3-latest.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.EntityLiving.die(EntityLiving.java:1420) ~[Paper-1.16.3-latest.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.EntityLiving.damageEntity(EntityLiving.java:1262) ~[Paper-1.16.3-latest.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.EntityHuman.attack(EntityHuman.java:1087) ~[Paper-1.16.3-latest.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.EntityPlayer.attack(EntityPlayer.java:1828) ~[Paper-1.16.3-latest.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2146) ~[Paper-1.16.3-latest.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[Paper-1.16.3-latest.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[Paper-1.16.3-latest.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[Paper-1.16.3-latest.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[Paper-1.16.3-latest.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[Paper-1.16.3-latest.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[Paper-1.16.3-latest.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[Paper-1.16.3-latest.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[Paper-1.16.3-latest.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[Paper-1.16.3-latest.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[Paper-1.16.3-latest.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[Paper-1.16.3-latest.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[Paper-1.16.3-latest.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[Paper-1.16.3-latest.jar:git-Paper-253]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]

**Comment by kingvonx** [comment]
if you read this thanks

**Comment by kingvonx** [comment]
I already fix the problem in source thanks
