### ISSUE TITLE
NullPointerException thrown during "break" task type

### ISSUE THREAD

**Issue by FesterHead** [FesterHead/Quests#5]
**Description of Error**
A NullPointerException is thrown for tasks of type `break`.

**To Reproduce**
This quest will reproduce the error:
```
tasks:
  task01:
    type: "break"
    amount: 10
    present: "break"
    past: "broken"
    #coreprotect: true
  task02:
    type: "place"
    amount: 10
    present: "place"
    past: "placed"
display:
  name: "Break and Place"
  type: "sand"
  lore-normal:
    - ""
    - "&7This quest requires:"
    - "{task01:complete} &7{task01:present} &b{task01:item}"
    - "{task02:complete} &7{task02:present} &b{task02:item}"
  lore-started:
    - ""
    - "&7Quest Progress:"
    - "{task01:remove}&f⇨ &7{task01:present} &6{task01:togo} &b{task01:item}"
    - "{task02:remove}&f⇨ &7{task02:present} &6{task02:togo} &b{task02:item}"
rewards:
  - "eco give {player} 1"
  - "give {player} dirt 1"
rewardstring:
  - "Quest completed."
options:
  category: "examples"
  repeatable: true
  cooldown:
    enabled: false
    time: 1440
  sort-order: 1
```

**Screenshots**
n/a

**Server (please complete the following information):**
 - Minecraft Version: 1.15.2
 - Mod Name: Paper 387
- Plugins (3): Essentials, Quests, Vault

**Plugin (please complete the following information):**
 - Version: 3.4.0

**Stacktrace**
```
[08:39:04 ERROR]: Could not pass event BlockBreakEvent to Quests v3.4.0-1.16.3
java.lang.NullPointerException: null
at com.leonardobishop.quests.quests.tasktypes.TaskType.processObject(TaskType.java:166) ~[?:?]
at com.leonardobishop.quests.quests.tasktypes.types.Break.onBlockBreak(Break.java:50) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1093.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-216]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-216]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-216]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-216]
at net.minecraft.server.v1_16_R2.PlayerInteractManager.breakBlock(PlayerInteractManager.java:324) ~[patched_1.16.3.jar:git-Paper-216]
at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:283) ~[patched_1.16.3.jar:git-Paper-216]
at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:249) ~[patched_1.16.3.jar:git-Paper-216]
at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1385) ~[patched_1.16.3.jar:git-Paper-216]
at net.minecraft.server.v1_16_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.16.3.jar:git-Paper-216]
at net.minecraft.server.v1_16_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.16.3.jar:git-Paper-216]
at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-216]
at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-216]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-216]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-216]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-216]
at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-216]
at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-216]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Paper-216]
at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.3.jar:git-Paper-216]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.3.jar:git-Paper-216]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-216]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
[08:39:04 ERROR]: Could not pass event BlockBreakEvent to Quests v3.4.0-1.16.3
```

**Comment by FesterHead** [comment]
Fixed in https://github.com/FesterHead/Quests/releases/tag/v3.4.2
