### ISSUE TITLE
error

### ISSUE THREAD

**Issue by kingvonx** [FesterHead/Quests#9]
[16:05:02 ERROR]: Could not pass event EntityDeathEvent to Quests v3.4.3-1.16.3
java.lang.NullPointerException: null
        at com.leonardobishop.quests.player.questprogressfile.QuestProgressFile.getQuestProgress(QuestProgressFile.java:341) ~[?:?]
        at com.leonardobishop.quests.quests.tasktypes.TaskType.processObject(TaskType.java:124) ~[?:?]
        at com.leonardobishop.quests.quests.tasktypes.types.Death.onMobKill(Death.java:43) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor635.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-251]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-251]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-251]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-251]
        at com.bgsoftware.wildstacker.listeners.L.L(mj:299) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Paper-251]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1296) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-251]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]

**Comment by kingvonx** [comment]
I already fix the problem in source thanks
